### ISSUE TITLE
Front End Courses to be completed

### ISSUE THREAD

**Issue by shingsay** [shingsay/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Front End Course*

* [ ] Git Hub Basics
* [ ] Debugging CSS With Chrome Dev Tools
* [ ] Responsive Layouts
* [ ] Practice Media Queries

:tada: :ok_man: :confetti_ball:
